name: Response Time Graph
on:
  workflow_run:
    workflows: ["Uptime CI"]
    types:
      - completed
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  response-time:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
