name: Static Site CI
on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Uptime CI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  static-site:
    name: Generate status page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: static-site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
