name: Uptime CI
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  uptime:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
